name: CI

on:
  push:
    branches: [ finaldrive ]
  pull_request:
    branches: [ finaldrive ]

  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, linux]

    if: github.ref == 'refs/heads/finaldrive'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run host
      - run: npm run dev

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user/aws_startpage-finaldrive
          remote_host: ec2-54-236-118-194.compute-1.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{ secrets.NOT_SAFE_FOR_LIFE }}"
